### ISSUE TITLE
Builds with package:lib-protobuf-host-3.3.0 fail

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-caffe#111]
Any Caffe build (e.g. `package:lib-caffe-bvlc-master-cuda-universal`) with `package:lib-protobuf-host-3.3.0` installed fails:
```
[  1%] Building CXX object src/caffe/CMakeFiles/caffeproto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
cd /home/anton/CK_TOOLS/lib-caffe-bvlc-master-cuda-trunk-gcc-5.4.0-linux-64/obj/src/caffe && /usr/bin/g++-5   -DCAFFE_VERSION=1.0.0 -I/home/anton/CK_TOOLS/lib-caffe-bvlc-master-cuda-trunk-gcc-5.4.0-linux-64/obj/include -I/usr/include/opencv -I/home/anton/CK_TOOLS/lib-caffe-bvlc-master-cuda-trunk-gcc-5.4.0-linux-64/obj -I/home/anton/CK_TOOLS/lib-protobuf-host-3.3.0-linux-64/install/include  -I/usr/include -fPIC -Wall -Wno-sign-compare -Wno-uninitialized -O3 -DNDEBUG   -o CMakeFiles/caffeproto.dir/__/__/include/caffe/proto/caffe.pb.cc.o -c /home/anton/CK_TOOLS/lib-caffe-bvlc-master-cuda-trunk-gcc-5.4.0-linux-64/obj/include/caffe/proto/caffe.pb.cc
In file included from /home/anton/CK_TOOLS/lib-caffe-bvlc-master-cuda-trunk-gcc-5.4.0-linux-64/obj/include/caffe/proto/caffe.pb.cc:5:0:
/home/anton/CK_TOOLS/lib-caffe-bvlc-master-cuda-trunk-gcc-5.4.0-linux-64/obj/include/caffe/proto/caffe.pb.h:25:60: fatal error: google/protobuf/generated_message_table_driven.h: No such file or directory
compilation terminated.
```

```
$ ck show env --tags=lib,protobuf-host,v3.3
Env UID:         Target OS: Bits: Name:                 Version: Tags:

aa8ae8e53ef4b575   linux-64    64 ProtoBuf host library 3.3.0    64bits,host-os-linux-64,lib,protobuf-host,target-os-linux-64,v3,v3.3,v3.3.0
```

**Comment by psyhtest** [comment]
A workaround is to use `lib-protobuf-host-3.1.0` (as currently hardcoded in the metadata) or `lib-protobuf-host-3.2.0`. Building with `lib-protobuf-host-trunk` also fails.
